### ISSUE TITLE
kubeconfig Environment Variable Size Limit on Windows

### ISSUE THREAD

**Issue by bdschaap** [HomecareHomebase/azure-bake#63]
My kubeconfig file is ~5K bytes and larger when base64 encoded.  Windows has a 1K limit on the size of an environment variable(?).  I'd like to propose supporting kubeconfig as a file location (via file path, url, etc).  I'm able to simply paste the base64 encoded contents in the Bake yaml as a workaround on Windows.

**Comment by whilke** [comment]
For local testing, we need a better way for building the BAKE_VARIABLE? data. When run through the ADO deployment task its fine since it builds in memory, saves to an env file that is passed to docker.

We probably need a local method of loading bake variables from a local file as an override for environment variables.

**Comment by bdschaap** [comment]
Makes sense on being just an issue with local testing.  I like the idea of loading variables from a file as an alternative to env vars.

**Comment by whilke** [comment]
Closing this out since bake_variables are now built from a local .env file instead of storing as an env variable.
